spring:
  datasource:
    url: jdbc:mysql://109.234.166.199:3306/riba6140_Kapiski?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: riba6140_pierre
    password: 0123456789Patate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  logging:
    level:
      root: INFO
      org.springframework: INFO
      your.package: DEBUG
      org.hibernate: WARN

